### ISSUE TITLE
Trouble with Command line

### ISSUE THREAD

**Issue by dmichaels2233** [lukaslangrock/ShutdownTimerClassic#10]
This looks great when I run it from the UI but when I try running from CMD, even as Admin, I get 
Access is denied.

I've changed directories and run 
Shutdowntimerclassic.exe with and without any arguments and result is always the same

This is where it resides:
(C:\Program Files\WindowsApps\19341LukasLangrock.ShutdownTimerClassic_1.2.2.0_x64__jnfph5tq58r4j\ShutdownTimer)

Any ideas?

**Comment by dmichaels2233** [comment]
Progress...

I copied the folder to another location (c:\temp) and it launched but then errored out.
Log file below:
[ShutdownTimerClassic Exception-Log [637542105133319466].txt](https://github.com/lukaslangrock/ShutdownTimerClassic/files/6328544/ShutdownTimerClassic.Exception-Log.637542105133319466.txt)

**Comment by lukaslangrock** [comment]
I get the same error. It seems like I changed something and forgot to update the CLI handler as well.

It works with [v1.2.0](https://github.com/lukaslangrock/ShutdownTimerClassic/releases/tag/v1.2.0) tho, you could try using that until I fixed the issue.

The permission problem you got is because apps from the MS-Store are managed by Windows and are not designed to be executed by the user directly. I recommend just downloading the GitHub release when using the CLI. It's not signed (you get an "unknown publisher" warning) but it's the exact same code.

**Comment by dmichaels2233** [comment]
Thank you for such a quick response.

David

**Comment by dmichaels2233** [comment]
Sorry, I tried 1.2.0 and while there is no error reported, I can’t seem to make it launch (start the countdown automatically).

 

cd C:\Program Files (x86)\Lukas Langrock\Shutdown Timer Classic

ShutdownTimerClassic.exe /SetTime 00:03:00 /SetAction Hibernate  /SetMode Launch

 

From: David Michaels ***@***.***> 
Sent: Saturday, April 17, 2021 11:36 AM
To: 'lukaslangrock/ShutdownTimerClassic' ***@***.***>; 'lukaslangrock/ShutdownTimerClassic' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [lukaslangrock/ShutdownTimerClassic] Trouble with Command line (#10)

 

Thank you for such a quick response.

David

**Comment by lukaslangrock** [comment]
Yes, that is because the CLI commands have changed.
This is your command for v1.2.0: `.\ShutdownTimerClassic.exe /SetTime 00:03:00 /SetAction Hibernate /Takeover`

To view the [older CLI commands in the README](https://github.com/lukaslangrock/ShutdownTimerClassic/tree/v1.2.0#cli-) you have to go back in time using the branch/tag switcher in the top left of the GitHub page and set it to the tag `v1.2.0`:
![grafik](https://user-images.githubusercontent.com/36658128/115120659-ee88ca00-9fae-11eb-9972-4fc54daf9cee.png)

**Comment by dmichaels2233** [comment]
Thank you – just one more question (sorry if I’m being a pain).

 

Is there a way to issue the command that will have the countdown display and not show the Shutdown timer launch/settings box?

It looks awesome.

 

David

**Comment by lukaslangrock** [comment]
Yeah, that was an issue with the older version. I had fixed that, but maybe some later changes before the release broke the CLI in the newer versions so these unusable. You can try `/Background` and just let the app run in the background with occasional notifications popping up.

**Comment by lukaslangrock** [comment]
Okay I think I fixed the CLI. It will take a while before I make the next release but you can try if the CLI works for you now with the development release: [ShutdownTimerClassicDEV.zip](https://github.com/lukaslangrock/ShutdownTimerClassic/files/6400270/ShutdownTimerClassicDEV.zip).

**Comment by dmichaels2233** [comment]
Hi Lukas,

 

Sorry to report that there are problems, or I am not running my batch file properly (hopefully it’s that).

 

My bat file looks like this:

echo off

cd "C:\Program Files (x86)\Lukas Langrock\Shutdown Timer Classic"

.\ShutdownTimerClassicDEV.exe /SetTime 00:04:00 /SetAction Hibernate /SetMode Launch

 

And I get this (below). 

Why 4 hours and 4 minutes instead of just 4 minutes?

Also, the timer didn’t display on screen.



 

Thanks 

David

**Comment by lukaslangrock** [comment]
No the issues appears to be within my application.
I've rushed the "fix" a bit and made some stupid mistakes... sry for that

**Comment by lukaslangrock** [comment]
Here, how is this?
[ShutdownTimerClassicDEV.zip](https://github.com/lukaslangrock/ShutdownTimerClassic/files/6416681/ShutdownTimerClassicDEV.zip)

**Comment by dmichaels2233** [comment]
No problem.

 

I look forward to trying out the revised code when it’s ready.

 

Thanks,

David

**Comment by dmichaels2233** [comment]
Sorry, I replied too quickly without noticing your latest E-mail.

 

THIS version works beautifully!

 

The background color is blue and doesn’t seem to change as described in the documentation. That’s not an issue for me, but I thought I’d mention it to make sure you’re aware.

 

Thanks very much, it’s really a very nice display.

 

Kind regards,

David

**Comment by lukaslangrock** [comment]
If the color stays at a constant light blue that means you have disabled animations under advanced settings.  
If you start it with the `/NoSettings` CLI paramater it should also go back to display animations as this would start the application with default settings.

**Comment by dmichaels2233** [comment]
That did it!

 

This is definitely the nicest countdown timer out there. 

I don’t know what else anyone could want from a countdown timer.

 

Clean look, small in size, flexible, runs from the co0mmand line or using the user interface.

 

Excellent!

 

Thanks,

David

**Comment by lukaslangrock** [comment]
Thank you very much ✨

**Comment by dmichaels2233** [comment]
I found a new problem that appears to be related to ShutdownTimerClassicDEV.

 

If ShutdownTimerClassic hibernates my machine and subsequently the machine wakes up dues to a scheduled task waking it up, the task will run, but the screen will not turn back on until you either click/move the mouse or use the keyboard.

 

If I Wake the machine manually, using the power button, the screen turns back on as expected.

 

Also, if the machine wakes up to run a scheduled task, it will go back to sleep after some short period of inactivity. The machine is not set to do that in the power options.

 

I noticed this behavior after running the app from a batch file as a scheduled task to put the machine into hibernation at night, but I reproduced the results running the app manually using your normal user interface.

 

Odd.

 

Thanks,

David 

 


Manual log created by ***@***.***
The following data includes information about your system and the internal state of the application at the time of log creation. You may remove certain information (like your username which may be included in the log) to protect your privacy.
This is NOT a crash! This log was created upon user request.


---- Process Info ----
PID: 7360
ProcessName: ShutdownTimerClassicDEV
Arguments: 
PriorityClass: Normal
Threads: 10
Responding: True
HasExited: False
StartTime: 5/9/2021 9:43:43 AM
PeakWorkingSet64: 40.8MB (42819584byte)
WorkingSet64: 40.8MB (42815488byte)
PeakWorkingSet64: 40.8MB (42819584byte)
PrivateMemorySize64: 20.8MB (21848064byte)
VirtualMemorySize64: 338.5MB (354979840byte)
PeakVirtualMemorySize64: 345.8MB (362639360byte)
PagedSystemMemorySize64: 565.8KB (579368byte)
NonpagedSystemMemorySize64: 30.6KB (31304byte)
PagedMemorySize64: 20.8MB (21848064byte)
PeakPagedMemorySize64: 20.8MB (21848064byte)
UserProcessorTime: 00:00:00.4375000
TotalProcessorTime: 00:00:00.9531250
PrivilegedProcessorTime: 00:00:00.5156250


---- Application Info ----
Product Name: ShutdownTimerClassicDEV
Product Version: 1.2.2.2
Current Culture: en-US
Executable Path: C:\Program Files (x86)\Lukas Langrock\Shutdown Timer Classic\ShutdownTimerClassicDEV.exe
MD5 Checksum: e00b53aef02283b1cce1e71a03a334c9


---- Environment Info ----
64-bit OS: True
64-bit Process: False
OS Version: Microsoft Windows NT 10.0.19042.0
Runtime Version: 4.0.30319.42000
System Uptime: 130968203
Machine Name: DAVLYNN2
Processor Count: 8
Shutdown Started: False


---- Internal Event Log ----
[Menu] Showing settings form
[Menu] Loading settings
[Menu] Showing form
[Menu] Setup finished
[Menu] Setting up form...
[Settings] Successfully loaded settings to an object in application memory
[Settings] Checked settings object
[Settings] Checking settings object
[Settings] Loading settings.json
[Settings] Loading settings...
[Program] Running Menu
[Program] Attaching ExceptionHandler.cs


---- End of Log ----

**Comment by lukaslangrock** [comment]
Hmm that is indeed odd, the app should not mess with anything like that since it only calls Windows' own APIs to execute the power action. This could be partly related to the app instructing Windows to not go into sleep mode.

Can you try unchecking the "Prevent system from going to sleep" checkbox or adding the `/AllowSleep` argument if you are launching from CLI?

**Comment by lukaslangrock** [comment]
Btw: The CLI fixes from the dev version are now live and released as [v1.2.3](https://github.com/lukaslangrock/ShutdownTimerClassic/releases/tag/v1.2.3). I have also changed the way the application talks to Windows after exiting, which might fix your issue with the screen staying black (if you disable the anti-sleep option when starting a countdown).

**Comment by lukaslangrock** [comment]
I'll assume the remaining issue is no longer relevant.
