### ISSUE TITLE
Need for a password for stopping timer

### ISSUE THREAD

**Issue by arcadien** [lukaslangrock/ShutdownTimerClassic#15]
To prevent kids to stop the timer by themselves.

**Comment by lukaslangrock** [comment]
You can use the **Password Protection** feature for this.  
Simply go into settings and, under the Advanced-tab, check the box labeled “Enable password protection”.

When you now start a countdown, there should be a dialogue asking for a password. After setting the password, the timer will start and not allow any modification until the correct password has been entered again.

*Please note that if your kid is smart enough to use Task Manager to stop the app, this will not prevent it. The password will only be useful for in-app actions.*
