### ISSUE TITLE
Shutdowntimer crashing on start up

### ISSUE THREAD

**Issue by Debscript324** [lukaslangrock/ShutdownTimerClassic#24]
[ShutdownTimerClassic Exception-Log [638027371282841884].txt](https://github.com/lukaslangrock/ShutdownTimerClassic/files/9895957/ShutdownTimerClassic.Exception-Log.638027371282841884.txt)

**Comment by lukaslangrock** [comment]
Tracking this problem in https://github.com/lukaslangrock/ShutdownTimerClassic/issues/30#issuecomment-1552688456 from now on.
