### ISSUE TITLE
Where are the executables?

### ISSUE THREAD

**Issue by VladOliinyk** [lukaslangrock/ShutdownTimerClassic#29]
Hello there!

I’m not afraid to seem like a little dummy boy, but, how can I start the app actually ?

**Comment by lukaslangrock** [comment]
It's fine, don't worry.

You can download and install most easily it through the Microsoft Store via this link: https://www.microsoft.com/store/apps/9NTDG6C9BTTW?cid=github.com

If you wish to download and run the executeable directly, it's available through [GitHub Releases](https://github.com/lukaslangrock/ShutdownTimerClassic/releases) (click on this link or go to the main page of this repo and look for *"Releases"* on the right side). On there, scroll down to *"Assets"* and choose between the raw binary and dependency bundle aka. the portable version, or the installer, which will copy the app and it's dependencies onto your system and create a shortcut on your Desktop. If you don't really know what this means, just click on the file with "Installer" in it's name, extract the downloaded ZIP-archive and click on one of the files.

I hope this helps :)
