### ISSUE TITLE
Shutdown Timer

### ISSUE THREAD

**Issue by ColonelFoxworth** [lukaslangrock/ShutdownTimerClassic#31]
---- Process Info ----
PID: 7944
ProcessName: ShutdownTimerClassic
Arguments: 
PriorityClass: Normal
Threads: 9
Responding: True
HasExited: False
StartTime: 03/22/2023 19:37:10
PeakWorkingSet64: 20.2MB (21176320byte)
WorkingSet64: 20.2MB (21172224byte)
PeakWorkingSet64: 20.2MB (21176320byte)
PrivateMemorySize64: 23.5MB (24608768byte)
VirtualMemorySize64: 198.4MB (208023552byte)
PeakVirtualMemorySize64: 198.4MB (208023552byte)
PagedSystemMemorySize64: 318.9KB (326536byte)
NonpagedSystemMemorySize64: 19.7KB (20152byte)
PagedMemorySize64: 23.5MB (24608768byte)
PeakPagedMemorySize64: 23.5MB (24608768byte)
UserProcessorTime: 00:00:00.1093750
TotalProcessorTime: 00:00:00.2500000
PrivilegedProcessorTime: 00:00:00.1406250

---- Application Info ----
Product Name: ShutdownTimerClassic
Product Version: 1.2.3.0
Current Culture: en-US
Executable Path: C:\ShutdownTimerClassic_v1.2.3.zip-fox-01-23-2023\ShutdownTimerClassic.exe
MD5 Checksum: f755519e89e2e543ed11f113634d6e20

---- Environment Info ----
64-bit OS: True
64-bit Process: False
OS Version: Microsoft Windows NT 10.0.19045.0
Runtime Version: 4.0.30319.42000
System Uptime: 4965703
Machine Name: ADMN-W10-PRO-64
Processor Count: 4
Shutdown Started: False

---- Exception ----
Type: UnhandledException
Message: Object reference not set to an instance of an object.
Stack Trace:
    at ShutdownTimer.Helpers.SettingsProvider.CheckSettings() in C:\Users\Lukas\repos\ShutdownTimerClassic\src\ShutdownTimer\Helpers\Settings.cs:line 62
   at ShutdownTimer.Helpers.SettingsProvider.Load() in C:\Users\Lukas\repos\ShutdownTimerClassic\src\ShutdownTimer\Helpers\Settings.cs:line 46
   at ShutdownTimer.Program.Main(String[] args) in C:\Users\Lukas\repos\ShutdownTimerClassic\src\ShutdownTimer\Program.cs:line 26

---- Internal Event Log ----
[Settings] Checking settings object
[Settings] Loading settings.json
[Settings] Loading settings...
[Program] Running Menu
[Program] Attaching ExceptionHandler.cs

---- End of Log ----

**Comment by lukaslangrock** [comment]
Tracking this problem in https://github.com/lukaslangrock/ShutdownTimerClassic/issues/30#issuecomment-1552688456 from now on.
