### ISSUE TITLE
Feature Request: Set Window Size

### ISSUE THREAD

**Issue by naucheesehead** [lukaslangrock/ShutdownTimerClassic#32]
I would be nice to be able to set window size or maybe have an option for a smaller timer window. Another idea would be to minimize the time and intergrate it into the Windows Taskbar.

**Comment by lukaslangrock** [comment]
The current design doesn't really take up a lot of screen space, I don't see how you could make it any smaller or how that would benefit anyone. Can you elaborate on how that would be useful?
As for the Taskbar integration, this would be kind of advanced, and I don't plan to support that, sorry.

But you can use the option to let the timer run in the background. That way, you have no screen space taken up by the countdown window, and you also get periodical notifications about how much time is left. Would that work for you?

**Comment by lukaslangrock** [comment]
As I don't see the benefit to changing the countdown window to be smaller and there already being an option to run in the background with a tray icon, I'll be closing this.
