### ISSUE TITLE
Feature request: disable confirmation dialogs

### ISSUE THREAD

**Issue by dangel666** [lukaslangrock/ShutdownTimerClassic#33]
If a timer is running and I close the app don't ask me first to confirm and then follow it with another dialog telling me it was cancelled.  Just close gracefully.

Happy if this is an option of course!

**Comment by lukaslangrock** [comment]
This feature is now implemented and handled using the setting to disable notifications, which now reads "Disable notifications and confirmations". It will be shipped with the next update.
