### ISSUE TITLE
Not a issue but a feature request

### ISSUE THREAD

**Issue by DouglasMoody** [lukaslangrock/ShutdownTimerClassic#37]
Enable timer reset on Mouse / cursor move.   Seems the Powercfg.cfg system in windows is blocked sometimes and system will remain running regardless of settings if say a video is paused in background.   So if this app could emulate the windows system by not activating until the mouse ceases movement then it would be a perfect addition/replacement.

**Comment by DouglasMoody** [comment]
I see this was reqeusted before , not seeing any direct option settings in the app for this.

**Comment by lukaslangrock** [comment]
Yeah, this was requested in #18, but the feature itself has not been implemented yet.
I was absent from this project for a decent time, but I'll try to implement this now.

**Comment by lukaslangrock** [comment]
I'll be closing this issue, as it's a partial duplicate. In case I post further updates, you can find them on the other issue or on the [roadmap](https://github.com/lukaslangrock/ShutdownTimerClassic/issues/19).
