### ISSUE TITLE
Critical Crash after starting App  with crack sounding via Soundsystem

### ISSUE THREAD

**Issue by Masato84** [lukaslangrock/ShutdownTimerClassic#39]
ShutdownTimerClassic@1.2.3 experienced a critical exception.
The following data includes information about your system, the exception and the internal state of the application at the time of the exception. You may remove certain information (like your username which may be included in the log) to protect your privacy.
Please open an issue on https://github.com/lukaslangrock/ShutdownTimerClassic and include the contents of this log file to help identify and fix the issue.

---- Process Info ----
PID: 1200
ProcessName: ShutdownTimerClassic
Arguments: 
PriorityClass: Normal
Threads: 9
Responding: True
HasExited: False
StartTime: 19.01.2024 00:59:57
PeakWorkingSet64: 22,4MB (23470080byte)
WorkingSet64: 22,4MB (23465984byte)
PeakWorkingSet64: 22,4MB (23470080byte)
PrivateMemorySize64: 13,5MB (14204928byte)
VirtualMemorySize64: 191,6MB (200921088byte)
PeakVirtualMemorySize64: 192,6MB (201986048byte)
PagedSystemMemorySize64: 290,8KB (297776byte)
NonpagedSystemMemorySize64: 20,7KB (21240byte)
PagedMemorySize64: 13,5MB (14204928byte)
PeakPagedMemorySize64: 13,5MB (14204928byte)
UserProcessorTime: 00:00:00.0937500
TotalProcessorTime: 00:00:00.2812500
PrivilegedProcessorTime: 00:00:00.1875000

---- Application Info ----
Product Name: ShutdownTimerClassic
Product Version: 1.2.3.0
Current Culture: de-DE
Executable Path: C:\Program Files\WindowsApps\19341LukasLangrock.ShutdownTimerClassic_1.2.3.0_x64__jnfph5tq58r4j\ShutdownTimer\ShutdownTimerClassic.exe
MD5 Checksum: f755519e89e2e543ed11f113634d6e20

---- Environment Info ----
64-bit OS: True
64-bit Process: False
OS Version: Microsoft Windows NT 10.0.19045.0
Runtime Version: 4.0.30319.42000
System Uptime: 119515
Machine Name: SYDOW
Processor Count: 8
Shutdown Started: False

---- Exception ----
Type: UnhandledException
Message: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Stack Trace:
    bei ShutdownTimer.Helpers.SettingsProvider.CheckSettings()
   bei ShutdownTimer.Helpers.SettingsProvider.Load()
   bei ShutdownTimer.Program.Main(String[] args)

---- Internal Event Log ----
[Settings] Checking settings object
[Settings] Loading settings.json
[Settings] Loading settings...
[Program] Running Menu
[Program] Attaching ExceptionHandler.cs

---- End of Log ----

**Comment by Masato84** [comment]
I couldnt start it afterwards i always get a security Issue template following this here.

**Comment by lukaslangrock** [comment]
This seems to be related to https://github.com/lukaslangrock/ShutdownTimerClassic/issues/30, I'll post updates if I eventually come back to working on this project again there. Thanks for the report tho.
