### ISSUE TITLE
Computer update

### ISSUE THREAD

**Issue by deffe23** [lukaslangrock/ShutdownTimerClassic#4]
What happens if I set a timer with Shutdown Timer Classic just as the computer is downloading and installing an update (so it will restart itself) ?

**Comment by lukaslangrock** [comment]
The newer versions of Windows leave the decision of when to restart to you and do not restart automatically during the set "active hours", at least in my experience. You can tweak Windows Update's restart behaviour and "active hours" in the Settings app.

Shutdown Timer Classic usually resists closing attempts by prompting the user with a message box (requires user interaction to exit) which would let Windows to interrupt a regular restart but **if Windows really wants to update, there is nothing my app can do about it**, as the the Windows Update restarts are usually forceful.

Also a good portion of updates don't require a restart and will be installed in the background, it's usually just the semi-annual feature updates that do this. But if Shutdown Timer Classic is executing a shutdown or restart and a Windows Update, which requires a restart, is queued for installation, **the Update will be installed when Shutdown Timer Classic (or any other process) initiates the shutdown/restart process**.

**Comment by deffe23** [comment]
Can you add name under the icon in windows start ? It would be very useful
![Uploading 20201007_174430.jpg…]()

**Comment by lukaslangrock** [comment]
Done!
