### ISSUE TITLE
startup crash on msi katana (laptop)

### ISSUE THREAD

**Issue by InfamousBugz** [lukaslangrock/ShutdownTimerClassic#40]
works fine on my desktop, crashes on my laptop.

---- Process Info ----
PID: 6076
ProcessName: ShutdownTimerClassic
Arguments: 
PriorityClass: Normal
Threads: 9
Responding: True
HasExited: False
StartTime: 4/4/2024 9:01:49 AM
PeakWorkingSet64: 23.9MB (25030656byte)
WorkingSet64: 23.9MB (25030656byte)
PeakWorkingSet64: 23.9MB (25030656byte)
PrivateMemorySize64: 13.8MB (14438400byte)
VirtualMemorySize64: 198.1MB (207769600byte)
PeakVirtualMemorySize64: 198.5MB (208097280byte)
PagedSystemMemorySize64: 300.9KB (308160byte)
NonpagedSystemMemorySize64: 23KB (23552byte)
PagedMemorySize64: 13.8MB (14438400byte)
PeakPagedMemorySize64: 13.8MB (14438400byte)
UserProcessorTime: 00:00:00.0781250
TotalProcessorTime: 00:00:00.1093750
PrivilegedProcessorTime: 00:00:00.0312500

---- Application Info ----
Product Name: ShutdownTimerClassic
Product Version: 1.2.3.0
Current Culture: en-US
Executable Path: C:\Program Files\WindowsApps\19341LukasLangrock.ShutdownTimerClassic_1.2.3.0_x64__jnfph5tq58r4j\ShutdownTimer\ShutdownTimerClassic.exe
MD5 Checksum: f755519e89e2e543ed11f113634d6e20

---- Environment Info ----
64-bit OS: True
64-bit Process: False
OS Version: Microsoft Windows NT 10.0.22631.0
Runtime Version: 4.0.30319.42000
System Uptime: 554933375
Machine Name: 
Processor Count: 16
Shutdown Started: False

---- Exception ----
Type: UnhandledException
Message: Object reference not set to an instance of an object.
Stack Trace:
    at ShutdownTimer.Helpers.SettingsProvider.CheckSettings()
   at ShutdownTimer.Helpers.SettingsProvider.Load()
   at ShutdownTimer.Program.Main(String[] args)

---- Internal Event Log ----
[Settings] Checking settings object
[Settings] Loading settings.json
[Settings] Loading settings...
[Program] Running Menu
[Program] Attaching ExceptionHandler.cs

---- End of Log ----

**Comment by lukaslangrock** [comment]
Thanks for the report. This problem is actually known, a workaround has been posted in https://github.com/lukaslangrock/ShutdownTimerClassic/issues/30#issuecomment-1552688456. Further discussion and updated will be posted there once I get back to work on this project again. Thanks again ^^

**Comment by InfamousBugz** [comment]
thanks, it worked!
