### ISSUE TITLE
Feature request: Full CLI version

### ISSUE THREAD

**Issue by hellishvictor** [lukaslangrock/ShutdownTimerClassic#42]
Hi, it would be awesome if there exist an CLI version without GUI of this, but which show the remaining time on cmd for use it on batch scripts.
Cheers.

**Comment by lukaslangrock** [comment]
Thanks for your feedback. While that does sound good, it won't be in scope for this project.
Given that I mainly use Linux nowadays, I already thought about a new project with separated CLI and GUI that would be cross-platform ready, but that I nothing more than an idea.
At the current time I won't be implementing this as this is meant to be a GUI-first application.
