### ISSUE TITLE
Crashing everytime I open Log File Below

### ISSUE THREAD

**Issue by Endergamer28742** [lukaslangrock/ShutdownTimerClassic#45]
[ShutdownTimerClassic Exception-Log [638630196214713800].txt](https://github.com/user-attachments/files/17171191/ShutdownTimerClassic.Exception-Log.638630196214713800.txt)

**Comment by lukaslangrock** [comment]
This issue seems to be a duplicate of #30, for which a fix has been implemented and is scheduled to roll out with the next update.
Thanks for your report.
