### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by isamuakira** [lukaslangrock/ShutdownTimerClassic#6]
ShutdownTimerClassic@1.2.0 experienced a critical exception.
The following data includes information about your system, the exception and the internal state of the application at the time of the exception.
Please open an issue on https://github.com/LukasLangrock/ShutdownTimerClassic and include the contents this log file to help identify and fix the issue.

---- Process Info ----
PID: 4212
ProcessName: ShutdownTimerClassic
Arguments: 
PriorityClass: Normal
Threads: 10
Responding: True
HasExited: False
StartTime: 13/01/2021 23.12.22
PrivateMemorySize64: 18345984
VirtualMemorySize64 309768192
PagedMemorySize64 18345984
PeakWorkingSet64: 33132544
WorkingSet64: 33128448
UserProcessorTime: 00:00:00.1093750
TotalProcessorTime: 00:00:00.2656250
ProcessorAffinity: 4095

---- Application Info ----
You may remove information from here to protect your privacy.
Product Name: ShutdownTimerClassic
Product Version: 1.2.0.0
Current Culture: id-ID
Executable Path: C:\Program Files\WindowsApps\19341LukasLangrock.ShutdownTimerClassic_1.2.0.0_neutral__jnfph5tq58r4j\Shutdown Timer\ShutdownTimerClassic.exe

---- Environment Info ----
64-bit OS: True
64-bit Process: False
OS Version: Microsoft Windows NT 10.0.19042.0
Runtime Version: 4.0.30319.42000
System Uptime: 832812875
Machine Name: XYZ
Processor Count: 12
Shutdown Started: False

---- Exception ----
Message: Object reference not set to an instance of an object.
Stack Trace:
    at ShutdownTimer.Helpers.SettingsProvider.CheckSettings()
   at ShutdownTimer.Helpers.SettingsProvider.Load()
   at ShutdownTimer.Menu.LoadSettings()
   at ShutdownTimer.Menu.Menu_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

---- Internal Event Log ----
[Settings] Checking settings object
[Settings] Loading settings.json
[Menu] Load settings
[Menu] Load menu

---- End of Log ----

**Comment by lukaslangrock** [comment]
Hi and thanks for reporting this. There seems to be an error with reading the settings file. If the error is persistent a quick [reset of the application](https://support.microsoft.com/en-us/windows/repair-apps-and-programs-in-windows-10-e90eefe4-d0a2-7c1b-dd59-949a9030f317) should help.

1. Open _Start_ and search for "_Shutdown Timer Classic_"
2. Click "_App Settings_" in the detail view on the right of your search results. (Alternatively right-click the search result and hit "_App Settings_")
3. Scroll down and click the "_Reset_" button

This will reinstall the app and earse all app data. Any problems with the settings should get fixed as the settings file also gets wiped.

### May I ask you some questions so I can try to find the bug?

1. Was this your first time using the Shutdown Timer?
2. Have you done anything in the application that made it crash or did it crash as soon as the application started?
2. Have you gone into the settings and if so, do you remember what you changed?
3. Have you previously installed the app through GitHub releases before you downloaded it from the Microsoft Store?
4. Could you check if there are any files in "%APPDATA%\Shutdown Timer Classic"?

**Comment by lukaslangrock** [comment]
Closing due to lack of information.

**Comment by lukaslangrock** [comment]
Tracking this problem in https://github.com/lukaslangrock/ShutdownTimerClassic/issues/30#issuecomment-1552688456 from now on.
