### ISSUE TITLE
feature request: require password to stop, restart, or change timer once started

### ISSUE THREAD

**Issue by ericjung** [lukaslangrock/ShutdownTimerClassic#7]
I want to start Shutdown Timer and then prevent it from being changed/exited/stopped/restarted without a password. I realize the user could simply kill it in task manager, but I'm predicating this request on the fact that many children don't know (yet) know how to do that. The password could be stored in-memory -- no need to write it to disk and that would eliminate the need for encryption (i dont think you need to encrypt the  password in-memory).

A text input field above the start button: `Password: ` would suffice. Clicking one of the tray menu items, changing any inputs, stopping the timer, exiting the timer -- would all require the password to be typed.

**Comment by lukaslangrock** [comment]
Thanks for the issue, this sounds like a useful addition to the project.
I'll work on implementing it.

**Comment by lukaslangrock** [comment]
The feature is now implemented. I have changed it a bit from your original concept in regards on how to activate it.

I expect not many people will use this feature so adding a password field directly in the menu would consume space that willl be rarely used. Instead you can enable this feature in _Settings > Advanced > Password Protection_. Once enabled it will ask you for a password when starting a countdown. If you decide not to use it this time, you can just click cancel in the password popup.

It will display a lock icon in the top right corner of the countdown window. This indicates that the UI locked. If you click on it or try to execute any of the options, a password prompt will appear. Once you enter the password the UI will be unlocked. If you want to re-lock it you can just click on the little lock icon, which will now display an unlocked icon.

I hope this will suit your needs. I will probably be working on some different things before releasing the next update which will bring your new feature, but it shouldn't take too long.

**Comment by lukaslangrock** [comment]
Sorry for the extremely long wait, the update containing your feature request is now out and should be available on the Microsoft Store within the next few days. You can already try it out through [GitHub Releases](https://github.com/lukaslangrock/ShutdownTimerClassic/releases/tag/v1.2.2).
